apiVersion: argoproj.io/v1alpha1
kind: Application
metada:
  name: astonvilla-application
  namespace: argocd
spec:
  project: astonvilla
  destination:
    namespace: internship
    server: https://kubernetes.default.svc
  source:
    path: astonvilla-app
    repoURL: "https://github.com/nourchawebi/argocdmai.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

